ALTER TABLE `User` DROP FOREIGN KEY `User_tenantId_fkey`;

ALTER TABLE `User` ADD COLUMN `isSuperAdmin` BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE `User` MODIFY COLUMN `tenantId` VARCHAR(191) NULL;

ALTER TABLE `User` ADD CONSTRAINT `User_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
